# Generated by Django 3.0.5 on 2020-04-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wards',
            new_name='Ward',
        ),
    ]
