# Generated by Django 3.0.5 on 2020-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_covidhospital_testcenters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCenters',
            new_name='TestCenter',
        ),
    ]
