# Generated by Django 3.0.5 on 2020-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200502_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='pop_level',
            field=models.CharField(default='NA', max_length=100, verbose_name='Ward Population level'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='risk',
            field=models.CharField(default='NA', max_length=256, verbose_name='Ward Risk'),
        ),
    ]
