# Generated by Django 3.0.5 on 2020-04-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200424_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Lat')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Lat')),
            ],
        ),
        migrations.CreateModel(
            name='TestCenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Name')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Lat')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Lat')),
            ],
        ),
    ]
