# Generated by Django 3.0.5 on 2020-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200426_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='patients',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ward',
            name='risk',
            field=models.CharField(default='NA', max_length=256, verbose_name='Ward Name'),
        ),
    ]
